background {
    monitor =
    path = ~/Pictures/Wallpapers/wallpaper.jpg
    blur_passes = 3
    blur_size = 7
    brightness = 0.3
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = rgb(5bbfcf)
    inner_color = rgb(050a14)
    font_color = rgb(e8d5ff)
    fade_on_empty = false
    placeholder_text = <span foreground="##7de8f0">🔑 Password...</span>
    hide_input = false
    check_color = rgb(a78be0)
    fail_color = rgb(c0392b)
    fail_text = <i>$FAIL</i>
    capslock_color = rgb(eab308)
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<span foreground='##e8d5ff' font_desc='JetBrainsMono Nerd Font Bold 42'>$(date +"%H:%M")</span>"
    color = rgba(e8d5ffff)
    font_size = 42
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(a78be0cc)
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, -140
    halign = center
    valign = center
}
